### PR TITLE
fix: rm live streams from vods

### LINKED ISSUE #34: prevent current stream from showing up
notes from stream:
- i think the biggest thing was just that it's kinda useless, editing-wise
- ugly cause the thumbnail won't render?

### PR DESCRIPTION
**Pull request by Yash-Singh1**
Works locally for me, unfortunately the Twitch API doesn't have any metadata on whether the stream is live or not so we have to make a separate request to the streams route.

Fixes #34

### CODE REVIEW

**Comment by markflorkowski** [comment]
Addresses Issue #34

File: src/app/(components)/vods.tsx [hunk 1]
```diff
@@ -74,7 +98,23 @@ export const VODs = async (props: { username: string }) => {
...
+  ).then((response) => response.json());
+
+  const streamMap = new Map<string, boolean>();
+  (streams as TwitchStreamRequest).data.forEach((stream) => {
+    streamMap.set(stream.id, true);
+  });
+
+  const data = (response as TwitchVodRequest).data.filter((vod) => {
+    return !streamMap.has(vod.stream_id);
+  });
```
Comment (flbn) [inline src/app/(components)/vods.tsx]: haven't set up my env and i'm on my phone but it could look something like this:

```suggestion
const [
  { data: vodData }, 
  { data: streamData }
] = await Promise.all([
  fetch(`https://api.twitch.tv/helix/videos?user_id=${twitchUserId}`, {
    method: "GET",
    headers: generateTwitchRequestHeaders(creds),
    redirect: "follow",
  }).then((response) => response.json()),
  fetch(`https://api.twitch.tv/helix/streams?user_id=${twitchUserId}&type=live`, {
    method: "GET",
    headers: generateTwitchRequestHeaders(creds),
    redirect: "follow",
  }).then((response) => response.json())
]);

const streamMap = new Map<string, boolean>(streamData.map((stream) => [stream.id, true]));

const filteredVodData = vodData.filter(({ stream_id }) => !streamMap.has(stream_id));
```

Comment (flbn) [reply src/app/(components)/vods.tsx]: probably fucked something up there so don't copy/paste. on the bus rn lol

Comment (Yash-Singh1) [reply src/app/(components)/vods.tsx]: alr ima test it out

Comment (Yash-Singh1) [reply src/app/(components)/vods.tsx]: 840985e676d1950aefbd0875e606122d991e6ab0

Comment (flbn) [reply src/app/(components)/vods.tsx]: noice, looks pretty

**Review by markflorkowski — APPROVED** [review]

**Comment by flbn** [comment]
only nit from the fix i have is that you should probably add some error handling. there's some stuff you could do like wrapping the promise in a `.catch()` and/or adding a `if(!response.ok) throw` for each fetch.

or, if they want more granular diagnostics maybe worth just popping `Promise.allSettled()` instead of `Promise.all()`

**Comment by t3dotgg** [comment]
I'd prefer allSettled, I'm pretty anti-All

**Comment by nickserv** [comment]
This doesn't have the issue #34 linked

**Comment by Yash-Singh1** [comment]
Fixes #34
